import { zodResolver } from "@hookform/resolvers/zod";
import { useEffect, useState, type ReactNode } from "react";
import { useForm } from "react-hook-form";
import { Link } from "react-router-dom";
import { z } from "zod";
import { api, ApiError } from "../api";

const schema = z.object({ email: z.string().email("Enter a valid email address."), username: z.string().regex(/^[a-zA-Z0-9_]{3,30}$/, "Use 3–30 letters, numbers, or underscores."), password: z.string().min(12, "Use at least 12 characters.").regex(/[a-z]/, "Include a lowercase letter.").regex(/[A-Z]/, "Include an uppercase letter.").regex(/[0-9]/, "Include a number.").regex(/[^a-zA-Z0-9]/, "Include a special character."), confirmPassword: z.string() }).refine((data) => data.password === data.confirmPassword, { path: ["confirmPassword"], message: "Passwords do not match." });
type FormValues = z.infer<typeof schema>;

export function RegisterPage() {
  const { register, handleSubmit, watch, formState: { errors, isSubmitting } } = useForm<FormValues>({ resolver: zodResolver(schema), mode: "onBlur" });
  const username = watch("username"); const [availability, setAvailability] = useState<"idle" | "checking" | "available" | "taken">("idle"); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { if (!/^[a-zA-Z0-9_]{3,30}$/.test(username ?? "")) { setAvailability("idle"); return; } setAvailability("checking"); const timeout = window.setTimeout(() => { void api<{ available: boolean }>(`/api/auth/username-availability?username=${encodeURIComponent(username.toLowerCase())}`).then((result) => setAvailability(result.available ? "available" : "taken")).catch(() => setAvailability("idle")); }, 350); return () => window.clearTimeout(timeout); }, [username]);
  async function submit(values: FormValues) { setMessage(null); setError(null); try { const response = await api<{ message: string }>("/api/auth/register", { method: "POST", body: JSON.stringify(values) }); setMessage(response.message); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "Unable to create your account."); } }
  return <section className="form-wrap"><p className="eyebrow">CREATE YOUR ACCOUNT</p><h1>Make it yours.</h1>{message ? <div className="notice success"><strong>Check your inbox.</strong><p>{message} In local development, open <a href="http://127.0.0.1:8025">Mailpit</a>.</p></div> : <form onSubmit={handleSubmit(submit)} noValidate><Field label="Email address" error={errors.email?.message}><input autoComplete="email" type="email" {...register("email")} /></Field><Field label="Username" error={errors.username?.message}><input autoComplete="username" {...register("username")} />{availability !== "idle" && <small className={availability === "taken" ? "taken" : "available"}>{availability === "checking" ? "Checking…" : availability === "available" ? "Username is available" : "Username is already taken"}</small>}</Field><Field label="Password" error={errors.password?.message}><input autoComplete="new-password" type="password" {...register("password")} /></Field><Field label="Confirm password" error={errors.confirmPassword?.message}><input autoComplete="new-password" type="password" {...register("confirmPassword")} /></Field>{error && <p className="form-error">{error}</p>}<button className="button" disabled={isSubmitting || availability === "taken"} type="submit">{isSubmitting ? "Creating account…" : "Create account"}</button></form>}<p className="form-footer">Already have an account? <Link to="/login">Sign in</Link></p></section>;
}
function Field({ label, error, children }: { label: string; error?: string; children: ReactNode }) { return <label className="field"><span>{label}</span>{children}{error && <small className="field-error">{error}</small>}</label>; }
