import { zodResolver } from "@hookform/resolvers/zod";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { Link, useSearchParams } from "react-router-dom";
import { z } from "zod";
import { api, ApiError } from "../api";

const emailSchema = z.object({ email: z.string().email("Enter a valid email address.") });
const passwordSchema = z.object({ password: z.string().min(12, "Use at least 12 characters.").regex(/[a-z]/, "Include a lowercase letter.").regex(/[A-Z]/, "Include an uppercase letter.").regex(/[0-9]/, "Include a number.").regex(/[^a-zA-Z0-9]/, "Include a special character."), confirmPassword: z.string() }).refine((data) => data.password === data.confirmPassword, { path: ["confirmPassword"], message: "Passwords do not match." });
type EmailValues = z.infer<typeof emailSchema>; type PasswordValues = z.infer<typeof passwordSchema>;

export function ResetPasswordPage() {
  const [params] = useSearchParams(); const token = params.get("token");
  return token ? <ChoosePassword token={token} /> : <RequestReset />;
}
function RequestReset() { const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<EmailValues>({ resolver: zodResolver(emailSchema) }); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); async function submit(values: EmailValues) { setError(null); try { const response = await api<{ message: string }>("/api/auth/password-reset/request", { method: "POST", body: JSON.stringify(values) }); setMessage(response.message); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "Unable to request a reset."); } } return <section className="form-wrap"><p className="eyebrow">ACCOUNT RECOVERY</p><h1>Reset password.</h1>{message ? <div className="notice success"><p>{message} Check <a href="http://127.0.0.1:8025">Mailpit</a> during local development.</p></div> : <form onSubmit={handleSubmit(submit)} noValidate><label className="field"><span>Email address</span><input autoComplete="email" type="email" {...register("email")} />{errors.email?.message && <small className="field-error">{errors.email.message}</small>}</label>{error && <p className="form-error">{error}</p>}<button className="button" disabled={isSubmitting} type="submit">{isSubmitting ? "Sending…" : "Send reset link"}</button></form>}<p className="form-footer"><Link to="/login">Back to sign in</Link></p></section>; }
function ChoosePassword({ token }: { token: string }) { const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<PasswordValues>({ resolver: zodResolver(passwordSchema) }); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); async function submit(values: PasswordValues) { setError(null); try { const response = await api<{ message: string }>("/api/auth/password-reset/confirm", { method: "POST", body: JSON.stringify({ token, password: values.password }) }); setMessage(response.message); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "Unable to reset password."); } } return <section className="form-wrap"><p className="eyebrow">CHOOSE A NEW PASSWORD</p><h1>Secure your account.</h1>{message ? <div className="notice success"><p>{message}</p><Link className="button" to="/login">Sign in</Link></div> : <form onSubmit={handleSubmit(submit)} noValidate><label className="field"><span>New password</span><input autoComplete="new-password" type="password" {...register("password")} />{errors.password?.message && <small className="field-error">{errors.password.message}</small>}</label><label className="field"><span>Confirm new password</span><input autoComplete="new-password" type="password" {...register("confirmPassword")} />{errors.confirmPassword?.message && <small className="field-error">{errors.confirmPassword.message}</small>}</label>{error && <p className="form-error">{error}</p>}<button className="button" disabled={isSubmitting} type="submit">{isSubmitting ? "Updating…" : "Update password"}</button></form>}</section>; }
